### ISSUE TITLE
2019/02/13 もくもく会 19:00-21:00

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/github-open-products#113]
## 連絡事項

- [x] 週末の定例会の日時場所を決める(@takahashi19 ) #109 
- [x] v1.0 版の見直し (@takahashi19 ) 
- [x] v1.0 に向けたタスクの振り直し(@tsu-nera )
- [x] プロジェクトタイトルの検討 (@tsu-nera ) #101 
- [x] メンバー勧誘状況の共有 (@tsu-nera @takahashi19 ) #110 

## 技術検討

- [x] Dependabotの導入検討(@tsu-nera ) #114 
- [x] Rollbar導入検討 (@tsu-nera ) #115 
- [x] GitHub API Clientの仕様すり合わせ(@tsu-nera @dh-megane ) #71 
- [x] プロジェクト募集終了時の扱い (@tsu-nera ) #116

**Comment by takahashi19** [comment]
場所：新宿三丁目
店：コーヒーラウンジレモン（珈琲は1杯600円ほど）
https://goo.gl/maps/7235sStw6HE2

**Comment by takahashi19** [comment]
## v1.0　再提案

- ユーザ認証機能
  - ログイン
  - サインイン
  - ログアウト
- トップページ(プロジェクト掲示板一覧でもよい)
- プロジェクト掲示板機能
  - 新規作成
  - 編集機能
  - 削除機能
  - 一覧表示機能
  - 個別表示機能
- メッセージ機能
  - 個別ペーシ掲示版機能(connpassみたいな）
- マイページ機能
  - SNSへのリンク(Twitterなど）
  - 個別情報登録(個人blog　URLとか、自己紹介とか、MENTAのイメージ）

**Comment by dh-megane** [comment]
【補足】
* トップページ
　→　プロジェクト掲示板一覧にする
* プロジェクト掲示板・個別表示機能
    →　自分がどのプロジェクトに参加しているかはv1.0では管理しない。
　　　コラボレーターの名前表示はひとまず保留。
  
* メッセージ機能
   個別ペーシ掲示版機能(connpassみたいな）
　@tsu-nera に担当してもらう

* マイページ機能
  欲しい機能はedit、show
  担当者は@takahashi19 @hiromoto-kazuya 
  今の機能が完了したらマイページ機能を担当してもらう予定。

@dh-megane 
　今の機能が完了した場合、「削除」「募集終了」の機能を割り当てたい。

【マイページ】
個別表示(show)と編集機能(edit)を検討。
どちらか担当するかは進捗具合。

【ログイン】
3/1時点のログイン機能はアプリで登録したアカウント（ユーザ名・パスワードを入力してもらう）
GitHubログインは後回し。

**Comment by tsu-nera** [comment]
議事メモありがとうございます。タスクとしてGitHubのissueに反映します。

このissueは閉じます。
